local function InitSN2ModSettings(ModState, debug_print)
    local SN2MS_NAME = "SprintOnLandMod"
    local SN2MS_DISPLAY = "Sprint On Land"
    local SN2MS_MANIFEST = "./ue4ss/Mods/SN2ModSettings/registrations/" .. SN2MS_NAME .. ".lua"

    local sn2msSettings = {
        { key="enabled", title="Enable Mod", type="toggle",
          description="Global toggle for the mod.",
          default=ModState.enabled, apply=function(v) ModState.enabled = v end },
        { key="sprint_multiplier", title="Sprint Speed Multiplier", type="slider", format="float",
          description="The multiplier applied to the character's base walk speed when sprinting.",
          default=ModState.sprint_multiplier, min=1.0, max=5.0, step=0.1,
          apply=function(v) ModState.sprint_multiplier = v end },
        { key="sprint_footstep_interval_ms", title="Min Walk Sound Interval (ms)", type="slider", format="integer",
          description="Limits how fast footstep sounds can play while sprinting to prevent audio spam. The game naturally steps every ~500ms when walking. Set to 300-450ms for a realistic running pace.",
          default=ModState.sprint_footstep_interval_ms, min=100, max=1000, step=10,
          apply=function(v) ModState.sprint_footstep_interval_ms = v end },
        { key="sprint_mode_toggle", title="Sprint Toggle Mode", type="toggle",
          description="If enabled, pressing the sprint key toggles sprint. If disabled, you must hold the key.",
          default=ModState.sprint_mode_toggle, apply=function(v) ModState.sprint_mode_toggle = v end },
        { key="update_interval_ms", title="Update Interval (ms)", type="slider", format="integer",
          description="How often to check for input. (Requires Mod Reload to take effect)",
          default=ModState.update_interval_ms, min=10, max=500, step=10,
          apply=function(v) ModState.update_interval_ms = v end },
        { key="debug", title="Enable Debug Logging", type="toggle",
          description="Print detailed logs to the console.",
          default=ModState.is_debug, apply=function(v) ModState.is_debug = v end },
        { key="SprintKey", title="Sprint Key", type="keybind",
          description="Primary key to trigger sprinting (Supports primary and alt keys).",
          default=(ModState.sprint_keys and ModState.sprint_keys[1]) or "LeftShift",
          default_alt=(ModState.sprint_keys and ModState.sprint_keys[2]) or "RightShift" },
    }

    local function sn2msWriteManifest()
        local dir = SN2MS_MANIFEST:match("(.*[/\\])")
        if dir then os.execute('mkdir "' .. dir:gsub("/", "\\") .. '" 2>nul') end
        local f = io.open(SN2MS_MANIFEST, "w")
        if not f then return end
        
        local p = {}
        p[#p+1] = "-- Auto-generated by SprintOnLandMod"
        p[#p+1] = "return {"
        p[#p+1] = string.format("    name     = %q,", SN2MS_NAME)
        if ModState.version then
            p[#p+1] = string.format("    version  = %q,", ModState.version)
        end
        p[#p+1] = string.format("    display  = %q,", SN2MS_DISPLAY)
        p[#p+1] = "    settings = {"
        for _, s in ipairs(sn2msSettings) do
            p[#p+1] = "        {"
            p[#p+1] = string.format("            key         = %q,", s.key)
            p[#p+1] = string.format("            title       = %q,", s.title)
            p[#p+1] = string.format("            description = %q,", s.description)
            p[#p+1] = string.format("            type        = %q,", s.type)
            if s.type == "toggle" then
                p[#p+1] = string.format("            default     = %s,", s.default and "true" or "false")
            elseif s.type == "keybind" then
                p[#p+1] = string.format("            default     = %q,", s.default)
                if s.default_alt then
                    p[#p+1] = string.format("            default_alt = %q,", s.default_alt)
                end
            else
                p[#p+1] = string.format("            default     = %s,", s.default)
                if s.min then p[#p+1] = string.format("            min         = %s,", s.min) end
                if s.max then p[#p+1] = string.format("            max         = %s,", s.max) end
                if s.step then p[#p+1] = string.format("            step        = %s,", s.step) end
                if s.format then p[#p+1] = string.format("            format      = %q,", s.format) end
            end
            p[#p+1] = "        },"
        end
        p[#p+1] = "    },"
        p[#p+1] = "}"
        f:write(table.concat(p, "\n"))
        f:close()

        -- Seed SN2ModSettings saved configuration if it doesn't exist to ensure Alt key defaults to RightShift
        local sn2msSavedPath = "./ue4ss/Mods/SN2ModSettings/saved/" .. SN2MS_NAME .. ".lua"
        local sf = io.open(sn2msSavedPath, "r")
        if not sf then
            local dir2 = sn2msSavedPath:match("(.*[/\\])")
            if dir2 then os.execute('mkdir "' .. dir2:gsub("/", "\\") .. '" 2>nul') end
            local wf = io.open(sn2msSavedPath, "w")
            if wf then
                local p2 = {}
                p2[#p2+1] = "-- Auto-generated defaults by SprintOnLandMod"
                p2[#p2+1] = "return {"
                if ModState.version then
                    p2[#p2+1] = string.format("    version = %q,", ModState.version)
                end
                p2[#p2+1] = string.format("    SprintKey = %q,", ModState.sprint_keys[1] or "LeftShift")
                if ModState.sprint_keys[2] then
                    p2[#p2+1] = string.format("    SprintKey_Alt = %q,", ModState.sprint_keys[2])
                end
                p2[#p2+1] = "}"
                wf:write(table.concat(p2, "\n"))
                wf:close()
                debug_print("[SprintOnLandMod] Seeded SN2ModSettings saved configuration with default keys.")
            end
        else
            sf:close()
        end
    end

    local sn2msLastApplied = {}
    
    local function sn2msPoll()
        if not ModRef then return end
        
        -- Update regular settings
        for _, s in ipairs(sn2msSettings) do
            if s.type ~= "keybind" then
                local ok, raw = pcall(function() return ModRef:GetSharedVariable("SN2ModSettings/" .. SN2MS_NAME .. "/" .. s.key) end)
                if ok and raw ~= nil then
                    local value
                    if s.type == "toggle" then
                        if type(raw) == "boolean" then value = raw
                        elseif type(raw) == "number" then value = raw ~= 0
                        elseif type(raw) == "string" then value = (raw == "true" or raw == "1") end
                    else
                        local n = (type(raw) == "number") and raw or tonumber(raw)
                        if n then value = n end
                    end
                    if value ~= nil and value ~= sn2msLastApplied[s.key] then
                        sn2msLastApplied[s.key] = value
                        if s.apply then
                            pcall(s.apply, value)
                            debug_print(string.format("[SprintOnLandMod] SN2ModSettings applied %s = %s", s.key, tostring(value)))
                        end
                    end
                end
            end
        end
        
        -- Update keybinds
        local ok, p = pcall(function() return ModRef:GetSharedVariable("SN2ModSettings/" .. SN2MS_NAME .. "/SprintKey") end)
        local ok2, a = pcall(function() return ModRef:GetSharedVariable("SN2ModSettings/" .. SN2MS_NAME .. "/SprintKey_Alt") end)
        
        local new_keys = {}
        if ok and type(p) == "string" and p ~= "" and p ~= "None" then table.insert(new_keys, p) end
        if ok2 and type(a) == "string" and a ~= "" and a ~= "None" then table.insert(new_keys, a) end
        
        if #new_keys > 0 then
            local changed = false
            if #new_keys ~= #ModState.sprint_keys then
                changed = true
            else
                for i=1, #new_keys do
                    if new_keys[i] ~= ModState.sprint_keys[i] then changed = true; break end
                end
            end
            
            if changed then
                ModState.sprint_keys = new_keys
                debug_print("[SprintOnLandMod] SN2ModSettings updated sprint keys: " .. table.concat(ModState.sprint_keys, ", "))
            end
        end
    end

    pcall(sn2msWriteManifest)
    return sn2msPoll
end

return InitSN2ModSettings
